src/WebDNA/Bundle/UserBundle/Form/Type/RecaptchaType.php
<?php

namespace WebDNA\Bundle\UserBundle\Form\Type;

use Symfony\Component\Form\AbstractType;

class RecaptchaType extends AbstractType
{
    public function getName()
    {
        return 'webdna_recaptcha';
    }
}

src/WebDNA/Bundle/UserBundle/Resources/views/Group/edit.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}
{% include "FOSUserBundle:Group:edit_content.html.twig" %}
{% endblock fos_user_content %}

src/WebDNA/Bundle/UserBundle/Resources/views/Group/edit_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

<form action="{{ path('fos_user_group_edit', {'groupName': group_name} ) }}" {{ form_enctype(form) }} method="POST" class="fos_user_group_edit">
    {{ form_widget(form) }}
    <div>
        <input type="submit" value="{{ 'group.edit.submit'|trans }}" />
    </div>
</form>

src/WebDNA/Bundle/UserBundle/Resources/views/Group/list.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}
{% include "FOSUserBundle:Group:list_content.html.twig" %}
{% endblock fos_user_content %}

src/WebDNA/Bundle/UserBundle/Resources/views/Group/list_content.html.twig
<div class="fos_user_group_list">
    <ul>
    {% for group in groups %}
        <li><a href="{{ path('fos_user_group_show', {'groupName': group.getName()} ) }}">{{ group.getName() }}</a></li>
    {% endfor %}
    </ul>
</div>

src/WebDNA/Bundle/UserBundle/Resources/views/Group/new.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}
{% include "FOSUserBundle:Group:new_content.html.twig" %}
{% endblock fos_user_content %}

src/WebDNA/Bundle/UserBundle/Resources/views/Group/new_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

<form action="{{ path('fos_user_group_new') }}" {{ form_enctype(form) }} method="POST" class="fos_user_group_new">
    {{ form_widget(form) }}
    <div>
        <input type="submit" value="{{ 'group.new.submit'|trans }}" />
    </div>
</form>

src/WebDNA/Bundle/UserBundle/Resources/views/Group/show.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}
{% include "FOSUserBundle:Group:show_content.html.twig" %}
{% endblock fos_user_content %}

src/WebDNA/Bundle/UserBundle/Resources/views/Group/show_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

<div class="fos_user_group_show">
    <p>{{ 'group.show.name'|trans }}: {{ group.getName() }}</p>
</div>